default:
  outputs:
    default:
      type: postgres
      host: localhost
      user: airflow
      password: airflow
      port: 5432
      dbname: postgres
      schema: public
      threads: 4

    prod:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
